name: Python application
on:
  push:
    branches:
      #- master
      - ci

# 在整个 workflow 中设置环境变量
env:
  # 自定义变量
  APPNAME: "tarpy"
  # 也可以引用 Contexts 或 Secrets
  #CACHE_KEY: ${{ github.sha }}
  CMD_TYPE: --dist
  CWD_DIR_IN: .

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - name: 跑起来～
      run: |
        echo "安装uv"
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv python install 3.14
        uv venv build-uv-venv
        source build-uv-venv/bin/activate
        echo "安装uv+启用虚拟环境"
        ls -lh
        echo "==================="
        uv pip install -r requirements.txt
        uv pip install -r requirements-build.txt
        pyinstaller tar.spec
        echo "==================="
        ls -lh
    
    - name: 运行测试
      run: |
        python tests/test.py -v > tests/test-result.txt 2>&1

    - name: 保存 ${{ env.APPNAME }}-${{ runner.os }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.APPNAME }}-${{ runner.os }}
        path: dist/${{ env.APPNAME}}

    - name: 保存 ${{ env.APPNAME }}-${{ runner.os }}-result.txt
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.APPNAME }}-${{ runner.os }}-result.txt
        path: tests/test-result.txt

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: 跑起来～
      run: |
        dir
        echo "==================="
        pip install -U --break-system-package -r requirements.txt
        pip install -U --break-system-package -r requirements-build.txt
        pyinstaller tar-win.spec
        echo "==================="
        dir

    - name: 运行测试
      run: |
        python tests/test.py -v > tests/test-result.txt 2>&1

    - name: 保存 ${{ env.APPNAME }}-${{ runner.os }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.APPNAME }}-${{ runner.os }}
        path: dist/${{ env.APPNAME }}.exe

    - name: 保存 ${{ env.APPNAME }}-${{ runner.os }}-result.txt
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.APPNAME }}-${{ runner.os }}-result.txt
        path: tests/test-result.txt
